module.exports = {
  SEARCH_BOOKS : "SEARCH_BOOKS",
  ADD_BOOK : "ADD_BOOK",
  UPDATE_BOOK : "UPDATE_BOOK",
  DELETE_BOOK : "DELETE_BOOK",
  CANCEL_BOOK_UPDATE : "CANCEL_BOOK_UPDATE",
  EDIT_LINK_UPDATE : "EDIT_LINK_UPDATE"

}
